# Generated by Django 3.2.7 on 2021-10-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'get_latest_by': ['nominations_start'], 'ordering': ['-nominations_start', 'admin_title']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='email_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
