# Generated by Django 3.2.7 on 2021-10-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society_elections', '0002_auto_20211001_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='manifesto',
            field=models.TextField(default='<no-manifesto>', help_text='Why you would be a good fit for the chosen position(s)'),
            preserve_default=False,
        ),
    ]
