# Generated by Django 3.2.7 on 2021-10-21 20:26

from django.db import migrations, models
import django.db.models.deletion
import society_elections.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('society_elections', '0004_remove_voter_email_salt'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousVoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.BinaryField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredVoter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, validators=[society_elections.validators.email_user_validator])),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
        migrations.AddField(
            model_name='election',
            name='anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='election',
            name='voter_verification_email',
            field=models.TextField(default='Click the link below or copy into your browser to verify your email address:\n\n{verify_url}', help_text="The message to send to voters to verify their email in the election. Format the message by using {email} for the voter's email address, and {verify_url} for the link to verify their email"),
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
        migrations.AddField(
            model_name='registeredvoter',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_voters', related_query_name='registered_voter', to='society_elections.election'),
        ),
        migrations.AddField(
            model_name='anonymousvoter',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_voters', related_query_name='anonymous_voter', to='society_elections.election'),
        ),
        migrations.AddField(
            model_name='vote',
            name='anonymous_voter',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='society_elections.anonymousvoter'),
        ),
        migrations.AddField(
            model_name='vote',
            name='registered_voter',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='society_elections.registeredvoter'),
        ),
    ]
