# Generated by Django 3.2.7 on 2021-11-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('society_elections', '0005_auto_20211021_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionposition',
            name='allow_abstain',
        ),
        migrations.RemoveField(
            model_name='electionposition',
            name='allow_ron',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='abstain',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='ron',
        ),
    ]
